const BLOCKS = {
  AIR: 0,
  GRASS: 1,
  DIRT: 2,
  STONE: 3,
  WOOD: 4,
  LEAVES: 5,
  SAND: 6,
  WATER: 7,
  LOG: 8,
  PLANKS: 9,
  COBBLESTONE: 10,
  GLASS: 11,
  BRICK: 12,
  COAL_ORE: 13,
  IRON_ORE: 14,
  GOLD_ORE: 15,
  DIAMOND_ORE: 16,
  BEDROCK: 17,
  GRAVEL: 18,
  SNOW: 19,
  ICE: 20,
  CACTUS: 21,
  WOOL_RED: 22,
  WOOL_BLUE: 23,
  WOOL_GREEN: 24,
  CRAFTING_TABLE: 25,
  FURNACE: 26,
  CHEST: 27,
  BOOKSHELF: 28,
  TORCH: 29,
  FLOWER: 30,
};

// Colors for each face: [top, bottom, left, right, front, back]
// or single color used for all faces
const BLOCK_COLORS = {
  [BLOCKS.GRASS]:    { top:'#5d9e3a', bottom:'#8b5a2b', side:'#8b5a2b', topOverlay:'#5d9e3a' },
  [BLOCKS.DIRT]:     { all:'#8b5a2b' },
  [BLOCKS.STONE]:    { all:'#888888' },
  [BLOCKS.WOOD]:     { all:'#8B4513' },
  [BLOCKS.LEAVES]:   { all:'#2d7a1a', transparent: true },
  [BLOCKS.SAND]:     { all:'#c8b56e' },
  [BLOCKS.WATER]:    { all:'#1a6bb5', transparent: true, alpha: 0.7 },
  [BLOCKS.LOG]:      { top:'#6b4c1e', bottom:'#6b4c1e', side:'#4a3010' },
  [BLOCKS.PLANKS]:   { all:'#c8a060' },
  [BLOCKS.COBBLESTONE]: { all:'#707070' },
  [BLOCKS.GLASS]:    { all:'#aaddff', transparent: true, alpha: 0.3 },
  [BLOCKS.BRICK]:    { all:'#8b4040' },
  [BLOCKS.COAL_ORE]: { all:'#888888', spots:'#222222' },
  [BLOCKS.IRON_ORE]: { all:'#888888', spots:'#c8a090' },
  [BLOCKS.GOLD_ORE]: { all:'#888888', spots:'#ffd700' },
  [BLOCKS.DIAMOND_ORE]: { all:'#888888', spots:'#00ffff' },
  [BLOCKS.BEDROCK]:  { all:'#444444' },
  [BLOCKS.GRAVEL]:   { all:'#999090' },
  [BLOCKS.SNOW]:     { top:'#ffffff', bottom:'#8b5a2b', side:'#ffffff' },
  [BLOCKS.ICE]:      { all:'#88ccff', transparent: true, alpha: 0.6 },
  [BLOCKS.CACTUS]:   { all:'#2d8a1a', side:'#1a7010' },
  [BLOCKS.WOOL_RED]: { all:'#cc3333' },
  [BLOCKS.WOOL_BLUE]: { all:'#3355cc' },
  [BLOCKS.WOOL_GREEN]: { all:'#336633' },
  [BLOCKS.CRAFTING_TABLE]: { top:'#8b6040', bottom:'#c8a060', side:'#9a7050' },
  [BLOCKS.FURNACE]:  { top:'#888888', bottom:'#888888', side:'#888888', front:'#664422' },
  [BLOCKS.CHEST]:    { all:'#c8a060', top:'#d4b070', border:'#8b6040' },
  [BLOCKS.BOOKSHELF]:{ top:'#c8a060', bottom:'#c8a060', side:'#4a3a80' },
  [BLOCKS.TORCH]:    { all:'#ffdd44' },
  [BLOCKS.FLOWER]:   { all:'#ff6688' },
};

const BLOCK_NAMES = {
  [BLOCKS.GRASS]: 'Трава',
  [BLOCKS.DIRT]: 'Земля',
  [BLOCKS.STONE]: 'Камень',
  [BLOCKS.WOOD]: 'Дерево',
  [BLOCKS.LEAVES]: 'Листья',
  [BLOCKS.SAND]: 'Песок',
  [BLOCKS.WATER]: 'Вода',
  [BLOCKS.LOG]: 'Бревно',
  [BLOCKS.PLANKS]: 'Доски',
  [BLOCKS.COBBLESTONE]: 'Булыжник',
  [BLOCKS.GLASS]: 'Стекло',
  [BLOCKS.BRICK]: 'Кирпич',
  [BLOCKS.COAL_ORE]: 'Угольная руда',
  [BLOCKS.IRON_ORE]: 'Железная руда',
  [BLOCKS.GOLD_ORE]: 'Золотая руда',
  [BLOCKS.DIAMOND_ORE]: 'Алмазная руда',
  [BLOCKS.BEDROCK]: 'Слой бедрока',
  [BLOCKS.GRAVEL]: 'Гравий',
  [BLOCKS.SNOW]: 'Снег',
  [BLOCKS.ICE]: 'Лёд',
  [BLOCKS.CACTUS]: 'Кактус',
  [BLOCKS.WOOL_RED]: 'Красная шерсть',
  [BLOCKS.WOOL_BLUE]: 'Синяя шерсть',
  [BLOCKS.WOOL_GREEN]: 'Зелёная шерсть',
  [BLOCKS.CRAFTING_TABLE]: 'Верстак',
  [BLOCKS.FURNACE]: 'Печь',
  [BLOCKS.CHEST]: 'Сундук',
  [BLOCKS.BOOKSHELF]: 'Книжная полка',
  [BLOCKS.TORCH]: 'Факел',
  [BLOCKS.FLOWER]: 'Цветок',
};

const BLOCK_EMOJIS = {
  [BLOCKS.GRASS]: '🟩', [BLOCKS.DIRT]: '🟫', [BLOCKS.STONE]: '⬜',
  [BLOCKS.WOOD]: '🪵', [BLOCKS.LEAVES]: '🌿', [BLOCKS.SAND]: '🏖️',
  [BLOCKS.WATER]: '🌊', [BLOCKS.LOG]: '🪵', [BLOCKS.PLANKS]: '📦',
  [BLOCKS.COBBLESTONE]: '🪨', [BLOCKS.GLASS]: '🔷', [BLOCKS.BRICK]: '🧱',
  [BLOCKS.COAL_ORE]: '🖤', [BLOCKS.IRON_ORE]: '🔶', [BLOCKS.GOLD_ORE]: '🌕',
  [BLOCKS.DIAMOND_ORE]: '💎', [BLOCKS.BEDROCK]: '⬛', [BLOCKS.GRAVEL]: '💠',
  [BLOCKS.SNOW]: '❄️', [BLOCKS.ICE]: '🧊', [BLOCKS.CACTUS]: '🌵',
  [BLOCKS.WOOL_RED]: '🟥', [BLOCKS.WOOL_BLUE]: '🟦', [BLOCKS.WOOL_GREEN]: '🟩',
  [BLOCKS.CRAFTING_TABLE]: '🔨', [BLOCKS.FURNACE]: '🔥', [BLOCKS.CHEST]: '📦',
  [BLOCKS.BOOKSHELF]: '📚', [BLOCKS.TORCH]: '🕯️', [BLOCKS.FLOWER]: '🌸',
};

const BLOCK_HARDNESS = {
  [BLOCKS.BEDROCK]: Infinity,
  [BLOCKS.STONE]: 7, [BLOCKS.COBBLESTONE]: 6,
  [BLOCKS.IRON_ORE]: 8, [BLOCKS.GOLD_ORE]: 8, [BLOCKS.DIAMOND_ORE]: 10,
  [BLOCKS.COAL_ORE]: 7,
  [BLOCKS.DIRT]: 3, [BLOCKS.GRASS]: 3, [BLOCKS.GRAVEL]: 3, [BLOCKS.SAND]: 3,
  [BLOCKS.WOOD]: 4, [BLOCKS.LOG]: 4, [BLOCKS.PLANKS]: 4, [BLOCKS.BOOKSHELF]: 4,
  [BLOCKS.LEAVES]: 1, [BLOCKS.FLOWER]: 1, [BLOCKS.TORCH]: 1,
  [BLOCKS.GLASS]: 2, [BLOCKS.ICE]: 3, [BLOCKS.SNOW]: 2,
  [BLOCKS.BRICK]: 6, [BLOCKS.CHEST]: 4, [BLOCKS.FURNACE]: 6,
  [BLOCKS.CRAFTING_TABLE]: 4, [BLOCKS.WATER]: 0, [BLOCKS.CACTUS]: 2,
  [BLOCKS.WOOL_RED]: 3, [BLOCKS.WOOL_BLUE]: 3, [BLOCKS.WOOL_GREEN]: 3,
};

// Default hotbar items
const DEFAULT_HOTBAR = [
  BLOCKS.GRASS, BLOCKS.STONE, BLOCKS.PLANKS, BLOCKS.LOG,
  BLOCKS.GLASS, BLOCKS.BRICK, BLOCKS.TORCH, BLOCKS.FLOWER, BLOCKS.SAND
];
