// ── НОВЫЕ БЛОКИ (расширение blocks.js) ──────────────────────────────────────

// Добавляем новые ID блоков
Object.assign(BLOCKS, {
  // Ад (Nether)
  OBSIDIAN:      40,
  NETHER_RACK:   41,
  NETHER_BRICK:  42,
  SOUL_SAND:     43,
  GLOWSTONE:     44,
  NETHER_PORTAL: 45,
  LAVA:          46,
  // Край (End)
  END_STONE:     47,
  PURPUR:        48,
  END_PORTAL_FRAME: 49,
  END_PORTAL:    50,
  // Деревня
  COBBLE_SLAB:   51,
  OAK_STAIRS:    52,
  GRAVEL_PATH:   53,
  MOSSY_COBBLE:  54,
  FENCE:         55,
  GLASS_PANE:    56,
  HAY_BALE:      57,
  BARREL:        58,
  // Подземелье
  MOSSY_STONE:   59,
  CHISELED_STONE:60,
  SPAWNER:       61,
  CHEST_TRAP:    62,
  // Декор
  PUMPKIN:       63,
  MELON:         64,
  WOOL_YELLOW:   65,
  WOOL_WHITE:    66,
});

// Цвета новых блоков
Object.assign(BLOCK_COLORS, {
  [BLOCKS.OBSIDIAN]:      { all:'#1a0a2a' },
  [BLOCKS.NETHER_RACK]:   { all:'#6a1a1a' },
  [BLOCKS.NETHER_BRICK]:  { all:'#2a0808' },
  [BLOCKS.SOUL_SAND]:     { all:'#3a2a1a', top:'#2a1a0a' },
  [BLOCKS.GLOWSTONE]:     { all:'#d4a840' },
  [BLOCKS.NETHER_PORTAL]: { all:'#7a00cc', transparent:true, alpha:0.7 },
  [BLOCKS.LAVA]:          { all:'#dd4400', transparent:true, alpha:0.9 },
  [BLOCKS.END_STONE]:     { all:'#d4d490' },
  [BLOCKS.PURPUR]:        { all:'#8a4a8a' },
  [BLOCKS.END_PORTAL_FRAME]:{ all:'#1a4a2a', top:'#004400' },
  [BLOCKS.END_PORTAL]:    { all:'#000820', transparent:true, alpha:0.85 },
  [BLOCKS.COBBLE_SLAB]:   { all:'#707070' },
  [BLOCKS.OAK_STAIRS]:    { all:'#c8a060' },
  [BLOCKS.GRAVEL_PATH]:   { all:'#aaa090', top:'#aa9a80' },
  [BLOCKS.MOSSY_COBBLE]:  { all:'#607060' },
  [BLOCKS.FENCE]:         { all:'#c8a060', transparent:true, alpha:0.9 },
  [BLOCKS.GLASS_PANE]:    { all:'#aaddff', transparent:true, alpha:0.3 },
  [BLOCKS.HAY_BALE]:      { all:'#c8a830', top:'#d4b840', side:'#b89820' },
  [BLOCKS.BARREL]:        { all:'#8b6040', top:'#6a4020' },
  [BLOCKS.MOSSY_STONE]:   { all:'#788878' },
  [BLOCKS.CHISELED_STONE]:{ all:'#aaaaaa' },
  [BLOCKS.SPAWNER]:       { all:'#224466', transparent:true, alpha:0.8 },
  [BLOCKS.CHEST_TRAP]:    { all:'#c84040', top:'#d45050' },
  [BLOCKS.PUMPKIN]:       { all:'#d4780a', top:'#8b5a0a' },
  [BLOCKS.MELON]:         { all:'#5a8a28', side:'#4a7a20' },
  [BLOCKS.WOOL_YELLOW]:   { all:'#ddcc22' },
  [BLOCKS.WOOL_WHITE]:    { all:'#eeeeee' },
});

// Имена
Object.assign(BLOCK_NAMES, {
  [BLOCKS.OBSIDIAN]:      'Обсидиан',
  [BLOCKS.NETHER_RACK]:   'Незерак',
  [BLOCKS.NETHER_BRICK]:  'Нижний кирпич',
  [BLOCKS.SOUL_SAND]:     'Песок душ',
  [BLOCKS.GLOWSTONE]:     'Светокамень',
  [BLOCKS.NETHER_PORTAL]: 'Портал в ад',
  [BLOCKS.LAVA]:          'Лава',
  [BLOCKS.END_STONE]:     'Эндерный камень',
  [BLOCKS.PURPUR]:        'Пурпур',
  [BLOCKS.END_PORTAL_FRAME]:'Рамка портала',
  [BLOCKS.END_PORTAL]:    'Портал в Край',
  [BLOCKS.COBBLE_SLAB]:   'Плита',
  [BLOCKS.OAK_STAIRS]:    'Ступени',
  [BLOCKS.GRAVEL_PATH]:   'Грунтовая дорога',
  [BLOCKS.MOSSY_COBBLE]:  'Замшелый булыжник',
  [BLOCKS.FENCE]:         'Забор',
  [BLOCKS.GLASS_PANE]:    'Стеклянная панель',
  [BLOCKS.HAY_BALE]:      'Тюк сена',
  [BLOCKS.BARREL]:        'Бочка',
  [BLOCKS.MOSSY_STONE]:   'Замшелый камень',
  [BLOCKS.CHISELED_STONE]:'Тёсаный камень',
  [BLOCKS.SPAWNER]:       'Спавнер',
  [BLOCKS.CHEST_TRAP]:    'Ловушка-сундук',
  [BLOCKS.PUMPKIN]:       'Тыква',
  [BLOCKS.MELON]:         'Арбуз',
  [BLOCKS.WOOL_YELLOW]:   'Жёлтая шерсть',
  [BLOCKS.WOOL_WHITE]:    'Белая шерсть',
});

// Эмодзи
Object.assign(BLOCK_EMOJIS, {
  [BLOCKS.OBSIDIAN]:      '🟣',
  [BLOCKS.NETHER_RACK]:   '🔴',
  [BLOCKS.NETHER_BRICK]:  '🧱',
  [BLOCKS.SOUL_SAND]:     '💀',
  [BLOCKS.GLOWSTONE]:     '💡',
  [BLOCKS.NETHER_PORTAL]: '🌀',
  [BLOCKS.LAVA]:          '🌋',
  [BLOCKS.END_STONE]:     '🟡',
  [BLOCKS.PURPUR]:        '💜',
  [BLOCKS.END_PORTAL_FRAME]:'🔮',
  [BLOCKS.END_PORTAL]:    '⬛',
  [BLOCKS.GRAVEL_PATH]:   '🛤️',
  [BLOCKS.MOSSY_COBBLE]:  '🪨',
  [BLOCKS.FENCE]:         '🪵',
  [BLOCKS.HAY_BALE]:      '🌾',
  [BLOCKS.BARREL]:        '🛢️',
  [BLOCKS.SPAWNER]:       '👾',
  [BLOCKS.PUMPKIN]:       '🎃',
  [BLOCKS.MELON]:         '🍉',
  [BLOCKS.WOOL_YELLOW]:   '🟨',
  [BLOCKS.WOOL_WHITE]:    '⬜',
});

// Твёрдость
Object.assign(BLOCK_HARDNESS, {
  [BLOCKS.OBSIDIAN]:      50,
  [BLOCKS.NETHER_RACK]:   2,
  [BLOCKS.NETHER_BRICK]:  4,
  [BLOCKS.SOUL_SAND]:     3,
  [BLOCKS.GLOWSTONE]:     1,
  [BLOCKS.NETHER_PORTAL]: Infinity,
  [BLOCKS.LAVA]:          0,
  [BLOCKS.END_STONE]:     5,
  [BLOCKS.PURPUR]:        4,
  [BLOCKS.END_PORTAL_FRAME]: Infinity,
  [BLOCKS.END_PORTAL]:    Infinity,
  [BLOCKS.MOSSY_COBBLE]:  5,
  [BLOCKS.SPAWNER]:       Infinity,
  [BLOCKS.CHEST_TRAP]:    4,
  [BLOCKS.PUMPKIN]:       2,
  [BLOCKS.MELON]:         1,
  [BLOCKS.FENCE]:         4,
  [BLOCKS.HAY_BALE]:      1,
  [BLOCKS.BARREL]:        4,
  [BLOCKS.GLOWSTONE]:     1,
});
